# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/franchise
   
# HTTP Server
server:
  port: 4444   
# HTTP (Tomcat) port