spring:
  datasource:
    url: jdbc:mysql://localhost:3306/franchise
    username: root
    password: ascTlm25
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect